# Project 1: NEET-JEE Performance Analysis

## Phase 1: Dataset Understanding

---

### Objective

The objective of this notebook is to understand the dataset before performing any preprocessing or exploratory data analysis (EDA). We will examine the dataset structure, inspect data types, identify missing values and duplicate records, and summarize the available features. This foundational analysis ensures a clear understanding of the data and supports reliable downstream analysis.

---

In [12]:

# Import Required Libraries

import pandas as pd
import numpy as np

# Display Settings
pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", None)

print(" Environment Working Successfully!")
print("Pandas Version:", pd.__version__)
print("NumPy Version:", np.__version__)

 Environment Working Successfully!
Pandas Version: 2.3.3
NumPy Version: 2.3.5

## Load the Dataset

In this section, we load the original dataset from the raw data folder using a relative file path. Keeping the raw dataset unchanged is a good data science practice because it preserves the original data for reproducibility.

In [13]:
df = pd.read_csv("../data/raw/College_Admission.csv")

print("Dataset loaded successfully!")

Dataset loaded successfully!

In [14]:
df.head()

,student_id,age,gender,category,state,preferred_stream,entrance_exam,entrance_score,board_percentage,extracurricular_score,admission_probability,admission_status,scholarship_eligibility
0,250.99,17,other,general,odisha,management,cet,30,95.58,2,0.387,admitted,yes
1,250.99,20,other,ews,gujarat,agriculture,none,0,75.45,2,0.221,rejected,no
2,250.99,19,female,sc,uttar pradesh,pharmacy,cet,120,75.36,10,0.446,rejected,no
3,250.99,18,male,ews,meghalaya,arts,cet,179,52.49,2,0.174,admitted,no
4,250.99,18,male,sc,rajasthan,engineering,jee,295,92.48,7,0.634,admitted,yes

### Observation

The first five rows provide an initial understanding of the dataset structure, feature names, and sample records. The dataset has been loaded successfully and is ready for further exploration.

In [15]:
df.shape

(25000, 13)

### Observation

The dataset contains **25000 rows** and **13 columns**.

## Dataset Information

In this section, we examine the dataset structure, including the number of records, columns, data types, and memory usage. This helps us understand the quality and characteristics of the dataset before performing any preprocessing.

In [16]:
# Dataset Information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   student_id               25000 non-null  float64
 1   age                      25000 non-null  int64
 2   gender                   25000 non-null  object
 3   category                 25000 non-null  object
 4   state                    25000 non-null  object
 5   preferred_stream         25000 non-null  object
 6   entrance_exam            25000 non-null  object
 7   entrance_score           25000 non-null  int64
 8   board_percentage         25000 non-null  float64
 9   extracurricular_score    25000 non-null  int64
 10  admission_probability    25000 non-null  float64
 11  admission_status         25000 non-null  object
 12  scholarship_eligibility  25000 non-null  object
dtypes: float64(3), int64(3), object(7)
memory usage: 2.5+ MB

### Observation

The dataset contains multiple numerical and categorical features. The data types appear appropriate for initial analysis. Further inspection will determine whether preprocessing is required.

In [17]:
# Column Names
df.columns

Index(['student_id', 'age', 'gender', 'category', 'state', 'preferred_stream',
       'entrance_exam', 'entrance_score', 'board_percentage',
       'extracurricular_score', 'admission_probability', 'admission_status',
       'scholarship_eligibility'],
      dtype='object')

In [18]:
# Basic Statistics for Numerical Columns
df.describe()

,student_id,age,entrance_score,board_percentage,extracurricular_score,admission_probability
count,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000
mean,12500.500000,18.492440,77.879760,75.028014,4.990920,0.323997
std,7212.732314,1.116205,120.356125,14.438767,3.158942,0.142427
min,250.990000,17.000000,0.000000,50.440000,0.000000,0.041990
25%,6250.750000,17.000000,0.000000,62.550000,2.000000,0.219000
50%,12500.500000,18.000000,20.000000,75.070000,5.000000,0.319000
75%,18750.250000,19.000000,126.000000,87.640000,8.000000,0.419000
max,24750.010000,20.000000,634.000000,99.530000,10.000000,0.731010

### Observation

The numerical features include age, entrance score, board percentage, extracurricular score, admission probability, and student ID. The descriptive statistics provide insights into the central tendency, spread, and distribution of these variables. No abnormal values are identified at this stage, but further analysis using visualizations will help detect potential outliers.

In [19]:
#Basic Statistics for Categorical Columns
df.describe(include='object')

,gender,category,state,preferred_stream,entrance_exam,admission_status,scholarship_eligibility
count,25000,25000,25000,25000,25000,25000,25000
unique,3,5,26,12,4,2,2
top,other,st,rajasthan,management,none,rejected,no
freq,8387,5081,1031,2163,11288,16848,19946

### Observation

The missing value analysis helps identify incomplete records in the dataset. The presence or absence of missing values will determine whether data cleaning techniques such as imputation are required before further analysis.

In [20]:
# Check Missing Values
df.isnull().sum()

student_id                 0
age                        0
gender                     0
category                   0
state                      0
preferred_stream           0
entrance_exam              0
entrance_score             0
board_percentage           0
extracurricular_score      0
admission_probability      0
admission_status           0
scholarship_eligibility    0
dtype: int64

### Observation

The missing value analysis helps identify incomplete records in the dataset. The presence or absence of missing values will determine whether data cleaning techniques such as imputation are required before further analysis.

In [21]:
# Check Duplicate Records
df.duplicated().sum()

np.int64(0)

### Observation

Duplicate records may affect the reliability of statistical analysis and machine learning models. Identifying duplicate observations ensures better data quality before preprocessing.